spring:
  config:
    activate:
      on-profile: docker

  data:
    redis:
      host: moodly-redis
      port: 6379

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:moodly-kafka:29092}

  datasource:
    url: jdbc:mysql://moodly-notification-db:3306/moodly_notification?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

security:
  jwt:
    common:
      secret: ${JWT_SECRET}

user:
  service:
    url: ${USER_SERVICE_URL:http://moodly-user:8082}