services:
  moodly-auth-db:
    container_name: moodly-auth-db
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: moodly_auth
    extends:
      file: common-config.yml
      service: microservice-db-config

  moodly-auth:
    profiles: ["app"]
    build:
      context: ..
      dockerfile: auth-service/Dockerfile
    image: tsyundeveloper/moodly-auth:latest
    container_name: moodly-auth
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_NAME: auth-service
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:mysql://moodly-auth-db:3306/moodly_auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      moodly-auth-db:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: network-deploy-service

networks:
  moodly:
    driver: bridge

volumes:
  moodly_moodly-auth-db: {}
