services:
  moodly-redis:
    image: redis:7
    container_name: moodly-redis
    ports:
      - "6379:6379"
    extends:
      file: common-config.yml
      service: network-deploy-service

  moodly-auth-db:
    container_name: moodly-auth-db
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: moodly_auth
    volumes:
      - moodly_moodly-auth-db:/var/lib/mysql
    extends:
      file: common-config.yml
      service: microservice-db-config

  moodly-auth:
    profiles: ["app"]
    build:
      context: ..
      dockerfile: auth-service/Dockerfile
    image: tsyundeveloper/moodly-auth:latest
    container_name: moodly-auth
    # ports:
    #   - "8081:8081"
    expose:
      - "8081"
    environment:
      SPRING_APPLICATION_NAME: auth-service
      SPRING_PROFILES_ACTIVE: docker
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_ACCESS_TOKEN: ${JWT_ACCESS_TOKEN}
      JWT_REFRESH_TOKEN: ${JWT_REFRESH_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      moodly-auth-db:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: network-deploy-service

  moodly-user-db:
    container_name: moodly-user-db
    ports:
      - "3311:3306"
    environment:
      MYSQL_DATABASE: moodly_user
    volumes:
      - moodly_moodly-user-db:/var/lib/mysql
    extends:
      file: common-config.yml
      service: microservice-db-config

  moodly-user:
    profiles: ["app"]
    build:
      context: ..
      dockerfile: user-service/Dockerfile
    image: tsyundeveloper/moodly-user:latest
    container_name: moodly-user
    # ports:
    #   - "8082:8082"
    expose:
      - "8082"
    environment:
      SPRING_APPLICATION_NAME: user-service
      SPRING_PROFILES_ACTIVE: docker
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      NAVER_MAIL_USERNAME: ${NAVER_MAIL_USERNAME}
      NAVER_MAIL_PASSWORD: ${NAVER_MAIL_PASSWORD}
      APP_FRONTEND_BASE_URL: http://localhost:3000
    depends_on:
      moodly-user-db:
        condition: service_healthy
      moodly-redis:
        condition: service_started
    extends:
      file: common-config.yml
      service: network-deploy-service

  moodly-product-db:
    container_name: moodly-product-db
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: moodly_product
    volumes:
      - moodly_moodly-product-db:/var/lib/mysql
    extends:
      file: common-config.yml
      service: microservice-db-config

  moodly-product:
    profiles: ["app"]
    build:
      context: ..
      dockerfile: product-service/Dockerfile
    image: tsyundeveloper/moodly-product:latest
    container_name: moodly-product
    # ports:
    #   - "8083:8083"
    expose:
      - "8083"
    environment:
      SPRING_APPLICATION_NAME: product-service
      SPRING_PROFILES_ACTIVE: docker
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      moodly-product-db:
        condition: service_healthy
      moodly-redis:
        condition: service_started
    extends:
      file: common-config.yml
      service: network-deploy-service

  moodly-gateway:
    profiles: ["app"]
    build:
      context: ..
      dockerfile: gateway-service/Dockerfile
    image: tsyundeveloper/moodly-gateway:latest
    container_name: moodly-gateway
    # 외부 진입점은 Gateway만
    ports:
      - "8072:8072"
    environment:
      SPRING_APPLICATION_NAME: gateway-service
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      moodly-auth:
        condition: service_started
      moodly-user:
        condition: service_started
      moodly-product:
        condition: service_started
    extends:
      file: common-config.yml
      service: network-deploy-service

networks:
  moodly:
    driver: bridge

volumes:
  moodly_moodly-auth-db: {}
  moodly_moodly-user-db: {}
  moodly_moodly-product-db: {}
