spring:
  datasource:
    url: jdbc:h2:mem:testdb_user;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop

security:
  jwt:
    common:
      secret: "bW9vZGx5LXRlc3Qtand0LXNlY3JldC0yMDI2" # 테스트용 secret
      issuer: moodly-auth
      audience: moodly-api
      roles-claim: roles

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

cart-service:
  base_url: http://localhost:8084